server:
  port: 8091

spring:
  application:
    name: schools
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: "*Mareen7#"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

application:
  config:
    students-url: http://localhost:8222/api/v1/student

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0





