spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: students
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/student/**
          - id: schools
            uri: http://localhost:8091
            predicates:
              - Path=/api/v1/school/**
      x-forwarded:
        proto-enabled: true


eureka:
  client:
    register-with-eureka: false
server:
  port: 8222


management:
  tracing:
    sampling:
      probability: 1.0

